# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 606)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 711, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.open_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_2.addWidget(self.open_button)
        self.file_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.file_label.setObjectName("file_label")
        self.horizontalLayout_2.addWidget(self.file_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sort_field_comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.sort_field_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.sort_field_comboBox.setObjectName("sort_field_comboBox")
        self.sort_field_comboBox.addItem("")
        self.sort_field_comboBox.addItem("")
        self.sort_field_comboBox.addItem("")
        self.sort_field_comboBox.addItem("")
        self.sort_field_comboBox.addItem("")
        self.sort_field_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.sort_field_comboBox)
        self.sort_order_comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.sort_order_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.sort_order_comboBox.setObjectName("sort_order_comboBox")
        self.sort_order_comboBox.addItem("")
        self.sort_order_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.sort_order_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "inventory_sort"))
        self.open_button.setText(_translate("Form", "Open"))
        self.file_label.setText(_translate("Form", "<- Open a JSON file"))
        self.label.setText(_translate("Form", "Sort"))
        self.sort_field_comboBox.setItemText(0, _translate("Form", "ID"))
        self.sort_field_comboBox.setItemText(1, _translate("Form", "Name"))
        self.sort_field_comboBox.setItemText(2, _translate("Form", "Category"))
        self.sort_field_comboBox.setItemText(3, _translate("Form", "Quantity"))
        self.sort_field_comboBox.setItemText(4, _translate("Form", "Price"))
        self.sort_field_comboBox.setItemText(5, _translate("Form", "Restock date"))
        self.sort_order_comboBox.setItemText(0, _translate("Form", "Ascending"))
        self.sort_order_comboBox.setItemText(1, _translate("Form", "Descending"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
